"""Agent Memory Security Guard and Citation Validation.

Phase 27: Advanced RAG & Context Security.
Guarantees:
- Memory Write Guard: Scans new memories before persisting, preventing memory poisoning
- Memory Read Guard: Scans memories before feeding into LLM prompt
- Citation Validation: Confirms cited source documents & chunks actually exist in retrieved context
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, Any, Dict, List, Optional

if TYPE_CHECKING:
    from llmfirewall.firewall import Firewall

from llmfirewall.core.models import Action, Finding
from llmfirewall.rag.models import ContextItem, SourceProvenance
from llmfirewall.runtime.models import TrustLevel


class MemorySecurityGuard:
    """Protects agent memory stores against persistent instruction injection and data poisoning."""

    def __init__(self, firewall: Firewall) -> None:
        self.firewall = firewall

    def guard_write(
        self,
        memory_content: str,
        memory_id: Optional[str] = None,
        source: str = "agent_reflection",
    ) -> ContextItem:
        """Scan memory before writing to storage. Raises or blocks on malicious injection."""
        scan_context = {
            "source_type": "memory",
            "trust_level": TrustLevel.UNTRUSTED.value,
            "direction": "input",
        }
        res = self.firewall.check_prompt(memory_content, context=scan_context)
        if res.decision.action == Action.BLOCK:
            from llmfirewall.runtime.models import RuntimeSecurityError
            raise RuntimeSecurityError(
                f"Memory write blocked by security policy: {res.decision.reason}",
            )

        return ContextItem(
            content=memory_content,
            source_type="memory",
            trust_level=TrustLevel.CONTROLLED,
            provenance=SourceProvenance(source_id=memory_id or "mem-auto", connector="memory_store"),
            findings=res.findings,
        )

    def guard_read(self, memory_items: List[ContextItem]) -> List[ContextItem]:
        """Scan and filter stored memories before injection into reasoning context."""
        safe = []
        for mem in memory_items:
            res = self.firewall.check_prompt(mem.content, context={"source_type": "memory"})
            if res.decision.action != Action.BLOCK:
                safe.append(mem)
        return safe


class CitationValidator:
    """Validates citations generated by LLMs against actual retrieved context chunks."""

    def validate_citations(
        self,
        response_text: str,
        retrieved_items: List[ContextItem],
    ) -> Dict[str, Any]:
        """Verify that citations formatted as [Doc X] or source_id map to retrieved chunks."""
        # Find citations like [Doc 1], [Doc 2], [source: src-123]
        doc_refs = re.findall(r"\[(?:Doc|Document)\s*(\d+)\]", response_text, re.IGNORECASE)
        source_refs = re.findall(r"\[source:\s*([a-zA-Z0-9_-]+)\]", response_text, re.IGNORECASE)

        valid_citations = []
        hallucinated_citations = []

        total_retrieved = len(retrieved_items)
        for ref in doc_refs:
            idx = int(ref)
            if 1 <= idx <= total_retrieved:
                valid_citations.append(f"Doc {idx}")
            else:
                hallucinated_citations.append(f"Doc {idx}")

        known_sources = {it.provenance.source_id for it in retrieved_items}
        for sref in source_refs:
            if sref in known_sources:
                valid_citations.append(sref)
            else:
                hallucinated_citations.append(sref)

        is_valid = len(hallucinated_citations) == 0
        return {
            "is_valid": is_valid,
            "valid_citations": valid_citations,
            "hallucinated_citations": hallucinated_citations,
            "total_citations": len(doc_refs) + len(source_refs),
        }
