"""Normalized security finding lifecycle, fingerprinting, and state tracking for Phase 31."""

from enum import Enum
import hashlib
import time
from typing import Any, Dict, List, Optional
import uuid
from pydantic import BaseModel, ConfigDict, Field

from llmfirewall.core.models import Severity


class FindingStatus(str, Enum):
    """Normalized lifecycle states for security findings."""
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    MITIGATED = "MITIGATED"
    ACCEPTED = "ACCEPTED"
    RESOLVED = "RESOLVED"
    REOPENED = "REOPENED"
    EXPIRED = "EXPIRED"


class GovernanceFinding(BaseModel):
    """Normalized, auditable security finding with lifecycle tracking and stable fingerprinting.
    
    Invariants:
    1. Zero Raw Secret Storage: Fingerprints are derived strictly from normalized metadata.
    2. Lifecycle Traceability: Status transitions and timestamps are explicitly recorded.
    3. Multi-Run Correlation: The same flaw across CI runs shares an identical deterministic fingerprint.
    """
    model_config = ConfigDict(frozen=True, extra="forbid")

    finding_id: str = Field(default_factory=lambda: f"FINDING-{uuid.uuid4().hex[:8].upper()}")
    fingerprint: str = Field(..., description="Deterministic SHA-256 fingerprint for cross-run correlation.")
    status: FindingStatus = Field(default=FindingStatus.OPEN, description="Current lifecycle state.")
    severity: Severity = Field(default=Severity.MEDIUM, description="Assessed security severity.")
    category: str = Field(..., description="Attack or security category (e.g. prompt_injection, tool_abuse).")
    test_id: Optional[str] = Field(default=None, description="Correlating test identifier if generated by test.")
    rule_id: Optional[str] = Field(default=None, description="Correlating policy rule identifier if applicable.")
    resource: Optional[str] = Field(default=None, description="Protected resource or tool target.")
    description: str = Field(..., description="Sanitized, human-readable finding description.")
    first_seen: float = Field(default_factory=time.time, description="Epoch timestamp when first observed.")
    last_seen: float = Field(default_factory=time.time, description="Epoch timestamp of most recent observation.")
    owner: Optional[str] = Field(default=None, description="Designated owner or engineering team.")
    baseline_id: Optional[str] = Field(default=None, description="Baseline ID when finding was established.")
    related_tests: List[str] = Field(default_factory=list, description="Associated security test IDs.")
    waiver_id: Optional[str] = Field(default=None, description="Active waiver ID if risk is accepted.")
    acceptance_reason: Optional[str] = Field(default=None, description="Justification if accepted.")
    acceptance_expires_at: Optional[float] = Field(default=None, description="Expiration epoch of acceptance.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Safe auxiliary metadata (no secrets).")

    @staticmethod
    def compute_fingerprint(
        category: str,
        test_id: Optional[str] = None,
        rule_id: Optional[str] = None,
        resource: Optional[str] = None,
    ) -> str:
        """Derive a stable, secret-free cryptographic fingerprint from normalized attributes."""
        norm_cat = (category or "").strip().lower()
        norm_test = (test_id or "").strip()
        norm_rule = (rule_id or "").strip()
        norm_res = (resource or "").strip().lower()
        raw = f"{norm_cat}|{norm_test}|{norm_rule}|{norm_res}"
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:24]

    @classmethod
    def from_test_finding(
        cls,
        category: str,
        description: str,
        severity: Severity = Severity.MEDIUM,
        test_id: Optional[str] = None,
        rule_id: Optional[str] = None,
        resource: Optional[str] = None,
        owner: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> "GovernanceFinding":
        """Factory creating a new GovernanceFinding with deterministic fingerprint."""
        fp = cls.compute_fingerprint(
            category=category,
            test_id=test_id,
            rule_id=rule_id,
            resource=resource,
        )
        now = time.time()
        return cls(
            fingerprint=fp,
            status=FindingStatus.OPEN,
            severity=severity,
            category=category,
            test_id=test_id,
            rule_id=rule_id,
            resource=resource,
            description=description,
            first_seen=now,
            last_seen=now,
            owner=owner,
            related_tests=[test_id] if test_id else [],
            metadata=metadata or {},
        )

    def with_status(
        self,
        new_status: FindingStatus,
        owner: Optional[str] = None,
        reason: Optional[str] = None,
        expires_at: Optional[float] = None,
        waiver_id: Optional[str] = None,
    ) -> "GovernanceFinding":
        """Create a new finding instance with updated lifecycle state."""
        return GovernanceFinding(
            finding_id=self.finding_id,
            fingerprint=self.fingerprint,
            status=new_status,
            severity=self.severity,
            category=self.category,
            test_id=self.test_id,
            rule_id=self.rule_id,
            resource=self.resource,
            description=self.description,
            first_seen=self.first_seen,
            last_seen=time.time(),
            owner=owner or self.owner,
            baseline_id=self.baseline_id,
            related_tests=self.related_tests,
            waiver_id=waiver_id or self.waiver_id,
            acceptance_reason=reason or self.acceptance_reason,
            acceptance_expires_at=expires_at or self.acceptance_expires_at,
            metadata=self.metadata,
        )
