"""Container and aggregator for findings emitted by detectors."""

from typing import Any, Dict, Iterator, List, Optional
from pydantic import BaseModel, ConfigDict, Field

from llmfirewall.core.models import Finding, Severity, ThreatType


class FindingCollection(BaseModel):
    """Immutable collection and querying layer for detector findings."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    findings: List[Finding] = Field(default_factory=list, description="List of collected findings")
    errors: List[Dict[str, str]] = Field(
        default_factory=list,
        description="Non-fatal detector execution errors recorded during scan",
    )

    def __len__(self) -> int:
        return len(self.findings)

    def __iter__(self) -> Iterator[Finding]:
        return iter(self.findings)

    def __getitem__(self, index: int) -> Finding:
        return self.findings[index]

    @property
    def is_empty(self) -> bool:
        """True if no findings were collected."""
        return len(self.findings) == 0

    @property
    def has_errors(self) -> bool:
        """True if any detector encountered an execution failure."""
        return len(self.errors) > 0

    @property
    def max_severity(self) -> Optional[Severity]:
        """Returns the highest severity across all findings, or None if empty."""
        if not self.findings:
            return None
        return max(f.severity for f in self.findings)

    def filter_by_threat(self, threat_type: ThreatType) -> List[Finding]:
        """Filter findings by specific ThreatType."""
        return [f for f in self.findings if f.threat_type == threat_type]

    def filter_by_min_severity(self, min_severity: Severity) -> List[Finding]:
        """Filter findings whose severity meets or exceeds a given threshold."""
        return [f for f in self.findings if f.severity >= min_severity]

    def filter_by_detector(self, detector_name: str) -> List[Finding]:
        """Filter findings generated by a specific detector."""
        return [f for f in self.findings if f.detector_name == detector_name]
